import Menu from './components/Menu'

export const metadata = {
  title: 'Sistema de voluntarios',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="pt-br">
      
      <body>
        <Menu />
        {children}
      </body>
    </html>
  )
}
